package lexer.token;

public enum TokenType
{
    INT, FLOAT, BOOL, STRING, CHAR, BEGIN, END, FUNCTION, IF, OR, ELSE, FOR, WHILE, GOES, FROM, TO, CALL, RETURN, BREAK, TRUE, FALSE,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,SEPARATOR_COMMA, SEPARATOR_SEMICOLON, TYPE_COLON, QUOTE, //brace = {}, parentheses = (), bracket = []
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    AND, NOT,
    ARRAY,
    NEWLINE, EOF,
}
