package lexer.token;

public enum TokenType {
    INT, BEGIN, END, FUNCTION, IF, OR, ELSE, FOR, GOES, FROM, TO, CALL, RETURN,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF
}
